[env]
TERM = "xterm-256color"
XDG_CONFIG_HOME = "/Users/tmsquill/.config"
XDG_DATA_HOME = "/Users/tmsquill/.config"

[font]
size = 14.0

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "ReceiveChar" }
]

[scrolling]
history = 100000

[terminal.shell]
program = "/opt/homebrew/bin/nu"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"

[general]
import = ["/Users/tmsquill/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
